name: Deploy to Production (Render)

on:
  push:
    branches: [prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run type-check

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Run security audit
      run: npm audit

    - name: Create build commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -f dist/
        git commit -m "Build for production deployment [skip ci]" || echo "No changes to commit"

    - name: Push build
      run: git push origin HEAD:prod

    - name: Deploy to Render
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"branch":"prod","clearCache":"do_not_clear"}' \
          "${{ secrets.RENDER_DEPLOY_WEBHOOK }}"

    - name: Verify deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        curl --fail "${{ secrets.RENDER_APP_URL }}/health" || exit 1

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ Deployment successful"
        else
          echo "❌ Deployment failed"
          exit 1
        fi